name: pr-test

on: [push]

jobs:
  install:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Use nodejs
        uses: actions/setup-node@v2

      - name: restore workspace cache
        uses: actions/cache@master
        id: cache
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: node-modules-v2-${{ runner.os }}-${{ steps.node-version.outputs.version }}-${{ hashFiles('**/yarn.lock', 'patches/*.patch') }}
          restore-keys: |
            node-modules-v2-${{ runner.os }}-${{ steps.node-version.outputs.version }}-
            node-modules-v2-${{ runner.os }}-

      - run: yarn install --frozen-lockfile --network-timeout 9000000
        if: steps.cache.outputs.cache-hit != 'true'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          SKIP_DOWNLOAD_MEDIA_ENGINE: true

      - run: yarn build

      - run: yarn eslint `./bin/eslint-changed.js "src/**/*" --github main`
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}